
const API_BASE=`${window.location.origin}/api`;const PERF_PAGE_SIZE=10;const st={perf:[],page:1};
const ADMIN_TOKEN_KEY='must_admin_token';const ADMIN_USER_KEY='must_admin_user';
let adminToken=localStorage.getItem(ADMIN_TOKEN_KEY)||'';
const q=(id)=>document.getElementById(id);const esc=(v)=>String(v??'').replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const safe=(v,f='-')=>(v===null||v===undefined||v==='')?f:v;const fmt=(d)=>{if(!d)return'-';const t=new Date(d);return Number.isNaN(t.getTime())?'-':t.toLocaleString()};
const dur=(s,e)=>{if(!s)return'-';if(!e)return'Active';const ms=new Date(e)-new Date(s);if(Number.isNaN(ms)||ms<0)return'-';return `${Math.max(1,Math.round(ms/60000))} min`};
const pillStatus=(s)=>`<span class="pill ${String(s).toLowerCase()==='active'?'active':'ended'}">${esc(s||'-')}</span>`;
const pillRole=(r)=>{const role=String(r||'').toLowerCase();const cls=role==='presenter'?'presenter':(role==='admin'?'active':'student');return `<span class="pill ${cls}">${esc(r||'-')}</span>`};
const pillLog=(t)=>{const m=String(t||'').toLowerCase();let c='active';if(m==='error')c='ended';if(m==='warning'||m==='disconnection')c='student';if(m==='info')c='presenter';return `<span class="pill ${c}">${esc(m||'-')}</span>`};
const cls=(v,g,w,inv=false)=>{if(v===null||v===undefined||Number.isNaN(Number(v)))return'';const n=Number(v);if(!inv){if(n<=g)return'good';if(n<=w)return'warn';return'bad'}if(n>=g)return'good';if(n>=w)return'warn';return'bad'};
function msg(text,type='ok'){q('msg').innerHTML=`<div class="msg ${type}">${esc(text)}</div>`;setTimeout(()=>q('msg').innerHTML='',3200)}
function authHeaders(){return adminToken?{Authorization:`Bearer ${adminToken}`}:{}} 
function showLogin(){q('adminLoginModal').style.display='flex';q('adminLogoutBtn').style.display='none'}
function hideLogin(){q('adminLoginModal').style.display='none';q('adminLogoutBtn').style.display='inline-flex'}
function clearAdminSession(){adminToken='';localStorage.removeItem(ADMIN_TOKEN_KEY);localStorage.removeItem(ADMIN_USER_KEY);showLogin()}
async function get(url){const r=await fetch(url,{headers:authHeaders()});if(r.status===401){clearAdminSession();throw new Error('401')}if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
async function loginAdmin(){try{const username=q('adminUser').value.trim().toLowerCase();const password=q('adminPass').value;if(!username||!password){msg('Enter admin username and password','err');return}
const r=await fetch(`${API_BASE}/admin/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});
if(!r.ok){msg('Invalid admin credentials','err');return}
const data=await r.json();adminToken=data.token;localStorage.setItem(ADMIN_TOKEN_KEY,data.token);localStorage.setItem(ADMIN_USER_KEY,data.username||username);q('adminPass').value='';hideLogin();msg('Admin login successful','ok');refreshAll(true)}catch(e){console.error(e);msg('Admin login failed','err')}}
async function logoutAdmin(){try{if(adminToken){await fetch(`${API_BASE}/admin/logout`,{method:'POST',headers:authHeaders()})}}catch(_){ }clearAdminSession();msg('Logged out','ok')}
async function ensureAdminSession(){if(!adminToken){showLogin();return}try{await get(`${API_BASE}/admin/me`);hideLogin();refreshAll()}catch(_){showLogin()}}
function csvEsc(v){const s=String(v??'').replace(/\r?\n|\r/g,' ').trim();return `"${s.replace(/"/g,'""')}"`}
function exportMountToCsv(mountId,filePrefix){
const mount=q(mountId);if(!mount){msg('Export failed: section not found','err');return}
const table=mount.querySelector('table');if(!table){msg('Nothing to export in this section','err');return}
const rows=[...table.querySelectorAll('tr')].map(tr=>[...tr.querySelectorAll('th,td')].map(td=>csvEsc(td.innerText)));
if(!rows.length){msg('Nothing to export in this section','err');return}
const csv=rows.map(r=>r.join(',')).join('\n');
const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);
const a=document.createElement('a');const ts=new Date().toISOString().replace(/[:T]/g,'-').slice(0,19);
a.href=url;a.download=`${filePrefix}_${ts}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);
msg(`CSV exported: ${filePrefix}`,'ok')
}

async function loadOverview(){const d=await get(`${API_BASE}/admin/overview`);q('sActive').textContent=safe(d?.stats?.activeSessions,0);q('sClients').textContent=safe(d?.stats?.connectedClients,0);q('sUsers').textContent=safe(d?.stats?.totalUsers,0);q('sAttend').textContent=safe(d?.stats?.totalAttendance,0);
const rooms=Array.isArray(d?.activeRooms)?d.activeRooms:[];if(!rooms.length){q('liveMount').innerHTML='<div class="empty">No active rooms.</div>';return}
q('liveMount').innerHTML=`<div class="wrap"><table><thead><tr><th>Room</th><th>Host</th><th>Email</th><th>Students</th><th>Status</th><th>Created</th></tr></thead><tbody>${rooms.map(r=>`<tr><td><strong>${esc(safe(r.roomId))}</strong></td><td>${esc(safe(r.presenterName))}</td><td>${esc(safe(r.presenterEmail))}</td><td>${safe(r.studentCount,0)}</td><td>${pillStatus(r.status)}</td><td>${fmt(r.createdAt)}</td></tr>`).join('')}</tbody></table></div>`}

async function loadSessions(){const p=new URLSearchParams();const s=q('fSessStatus').value.trim();const x=q('fSessSearch').value.trim();if(s)p.append('status',s);if(x)p.append('search',x);const rows=await get(`${API_BASE}/sessions${p.toString()?`?${p}`:''}`);if(!rows.length){q('sessionsMount').innerHTML='<div class="empty">No sessions found.</div>';return}
q('sessionsMount').innerHTML=`<div class="wrap"><table><thead><tr><th>Room ID</th><th>Presenter</th><th>Title</th><th>Status</th><th>Participants</th><th>Created</th><th>Duration</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(safe(r.room_id))}</strong></td><td>${esc(safe(r.presenter_name))}</td><td>${esc(safe(r.title))}</td><td>${pillStatus(r.status)}</td><td>${safe(r.participant_count,0)}</td><td>${fmt(r.created_at)}</td><td>${dur(r.created_at,r.ended_at)}</td></tr>`).join('')}</tbody></table></div>`}

async function loadUsers(){const p=new URLSearchParams();const r=q('fUserRole').value.trim();const s=q('fUserSearch').value.trim();if(r)p.append('role',r);if(s)p.append('search',s);const rows=await get(`${API_BASE}/users${p.toString()?`?${p}`:''}`);if(!rows.length){q('usersMount').innerHTML='<div class="empty">No users found.</div>';return}
q('usersMount').innerHTML=`<div class="wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>IP Address</th><th>Created</th><th>Last Active</th></tr></thead><tbody>${rows.map(u=>`<tr><td>${esc(safe(u.name))}</td><td>${esc(safe(u.email))}</td><td>${pillRole(u.role)}</td><td>${esc(safe(u.socket_id))}</td><td>${fmt(u.created_at)}</td><td>${fmt(u.last_active)}</td></tr>`).join('')}</tbody></table></div>`}

async function loadContent(){const p=new URLSearchParams({limit:q('fContentLimit').value});const room=q('fContentRoom').value.trim();if(room)p.append('sessionId',room);const rows=await get(`${API_BASE}/admin/content-history?${p}`);if(!rows.length){q('contentMount').innerHTML='<div class="empty">No content history found.</div>';return}
q('contentMount').innerHTML=`<div class="wrap"><table><thead><tr><th>Started</th><th>Room</th><th>User</th><th>Type</th><th>Title</th><th>Current</th><th>Duration</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${fmt(r.started_at)}</td><td>${esc(safe(r.room_id))}</td><td>${esc(safe(r.user_name))}</td><td>${esc(safe(r.share_type))}</td><td>${esc(safe(r.content_title))}</td><td>${safe(r.current_slide,'-')}</td><td>${safe(r.duration_minutes,dur(r.started_at,r.ended_at))}</td></tr>`).join('')}</tbody></table></div>`}

async function reloadPerf(){const p=new URLSearchParams({limit:q('fPerfLimit').value});const room=q('fPerfRoom').value.trim();const t=q('fPerfType').value.trim();if(room)p.append('sessionId',room);if(t)p.append('logType',t);st.perf=await get(`${API_BASE}/admin/performance-logs?${p}`);st.page=1;renderPerf();}
function renderPerf(){const rows=st.perf||[];if(!rows.length){q('perfMount').innerHTML='<div class="empty">No performance logs found.</div>';q('perfPag').style.display='none';return}
const pages=Math.max(1,Math.ceil(rows.length/PERF_PAGE_SIZE));if(st.page>pages)st.page=pages;const from=(st.page-1)*PERF_PAGE_SIZE;const part=rows.slice(from,from+PERF_PAGE_SIZE);
q('perfMount').innerHTML=`<div class="wrap"><table><thead><tr><th>Time</th><th>Room</th><th>Participant</th><th>Type</th><th>Message</th><th>Latency</th><th>Throughput</th><th>Loss</th><th>Jitter</th></tr></thead><tbody>${part.map(l=>`<tr><td>${fmt(l.recorded_at)}</td><td><strong>${esc(safe(l.room_id))}</strong></td><td>${esc(safe(l.participant_name,'System'))}</td><td>${pillLog(l.log_type)}</td><td title="${esc(safe(l.message))}">${esc(safe(l.message))}</td><td class="${cls(l.latency_ms,80,180)}">${l.latency_ms==null?'-':Number(l.latency_ms).toFixed(1)+' ms'}</td><td class="${cls(l.throughput_mbps,3,1.5,true)}">${l.throughput_mbps==null?'-':Number(l.throughput_mbps).toFixed(2)+' Mbps'}</td><td class="${cls(l.packet_loss_pct,1,3)}">${l.packet_loss_pct==null?'-':Number(l.packet_loss_pct).toFixed(2)+'%'}</td><td class="${cls(l.jitter_ms,15,35)}">${l.jitter_ms==null?'-':Number(l.jitter_ms).toFixed(1)+' ms'}</td></tr>`).join('')}</tbody></table></div>`;
q('perfPag').style.display='flex';q('pInfo').textContent=`Page ${st.page} of ${pages} (${rows.length} rows)`;q('pPrev').disabled=st.page<=1;q('pNext').disabled=st.page>=pages;}
function goPerf(d){const pages=Math.max(1,Math.ceil((st.perf||[]).length/PERF_PAGE_SIZE));st.page=Math.min(pages,Math.max(1,st.page+d));renderPerf();}

async function loadFeedback(){const lim=q('fFbLimit').value;const rows=await get(`${API_BASE}/admin/feedback?limit=${lim}`);if(!rows.length){q('feedbackMount').innerHTML='<div class="empty">No feedback found.</div>';return}
q('feedbackMount').innerHTML=`<div class="wrap"><table><thead><tr><th>Time</th><th>User</th><th>Role</th><th>Rating</th><th>Issue</th><th>Description</th><th>Screenshot</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(f=>{const issue=safe(f.issue_type,'general');const description=safe(f.description||f.message);const currentStatus=String(f.status||'pending').toLowerCase();const viewStatus=currentStatus==='resolved'?'resolved':'viewed';const screenshotCell=f.screenshot_path?`<a href="#" onclick="markFeedbackStatus(${Number(f.id)},'${viewStatus}','${encodeURIComponent(String(f.screenshot_path))}');return false;">View</a>`:'-';const resolveBtn=currentStatus==='resolved'?'<span class="good">Resolved</span>':`<button class="btn btn-s" style="height:28px;padding:0 8px" onclick="markFeedbackStatus(${Number(f.id)},'resolved')">Resolve</button>`;return `<tr><td>${fmt(f.created_at)}</td><td>${esc(safe(f.user_name,'Unknown'))}</td><td>${pillRole(f.user_role||'student')}</td><td>${safe(f.rating,'-')}</td><td>${esc(issue)}</td><td title="${esc(description)}">${esc(description)}</td><td>${screenshotCell}</td><td>${esc(safe(f.status,'pending'))}</td><td>${resolveBtn}</td></tr>`}).join('')}</tbody></table></div>`}

async function markFeedbackStatus(feedbackId,status,screenshotPath=''){try{const r=await fetch(`${API_BASE}/admin/feedback/${feedbackId}/status`,{method:'POST',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify({status})});if(r.status===401){clearAdminSession();throw new Error('401')}const data=await r.json();if(!r.ok)throw new Error(data.error||'Failed to update feedback status');if(screenshotPath){window.open(decodeURIComponent(screenshotPath),'_blank','noopener')}loadFeedback()}catch(e){console.error(e);msg(e.message||'Failed to update feedback status','err')}}
async function runRetentionCleanup(){try{const confirmationCode=q('dangerCode').value.trim();const retentionDays=Number(q('retentionDays').value||30);if(!confirmationCode){msg('Enter the admin confirmation code first','err');return}const r=await fetch(`${API_BASE}/admin/maintenance/cleanup`,{method:'POST',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify({confirmationCode,retentionDays})});if(r.status===401){clearAdminSession();throw new Error('401')}const data=await r.json();if(!r.ok)throw new Error(data.error||'Cleanup failed');msg('Automatic cleanup completed','ok');refreshAll(true)}catch(e){console.error(e);msg(e.message||'Cleanup failed','err')}}
async function wipeOperationalData(){try{const confirmationCode=q('dangerCode').value.trim();if(!confirmationCode){msg('Enter the admin confirmation code first','err');return}if(!confirm('Delete all classroom data from users, sessions, attendance, feedback, performance logs, and content history?'))return;const r=await fetch(`${API_BASE}/admin/maintenance/wipe`,{method:'POST',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify({confirmationCode})});if(r.status===401){clearAdminSession();throw new Error('401')}const data=await r.json();if(!r.ok)throw new Error(data.error||'Delete failed');msg('All classroom data deleted successfully','ok');refreshAll(true)}catch(e){console.error(e);msg(e.message||'Delete failed','err')}}
async function deleteSelectedTable(){try{const confirmationCode=q('dangerCode').value.trim();const tableName=q('dangerTable').value;if(!confirmationCode){msg('Enter the admin confirmation code first','err');return}if(!tableName){msg('Choose a table first','err');return}if(!confirm(`Delete all rows from ${tableName}?`))return;const r=await fetch(`${API_BASE}/admin/maintenance/delete-table`,{method:'POST',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify({confirmationCode,tableName})});if(r.status===401){clearAdminSession();throw new Error('401')}const data=await r.json();if(!r.ok)throw new Error(data.error||'Delete failed');msg(`Deleted data from ${tableName}`,'ok');refreshAll(true)}catch(e){console.error(e);msg(e.message||'Delete failed','err')}}

async function refreshAll(toast=false){try{await Promise.all([loadOverview(),loadSessions(),loadUsers(),loadContent(),reloadPerf(),loadFeedback()]);q('lastRef').textContent=`Updated ${new Date().toLocaleTimeString()}`;if(toast)msg('Dashboard refreshed','ok')}catch(e){console.error(e);msg('Failed to load dashboard data','err')}}

q('fSessStatus').addEventListener('change',loadSessions);q('fUserRole').addEventListener('change',loadUsers);q('fContentLimit').addEventListener('change',loadContent);q('fPerfType').addEventListener('change',reloadPerf);q('fPerfLimit').addEventListener('change',reloadPerf);q('fFbLimit').addEventListener('change',loadFeedback);
['fSessSearch','fUserSearch','fContentRoom','fPerfRoom'].forEach(id=>q(id).addEventListener('input',()=>{clearTimeout(window[id]);window[id]=setTimeout(()=>({fSessSearch:loadSessions,fUserSearch:loadUsers,fContentRoom:loadContent,fPerfRoom:reloadPerf}[id]()),250)}));

q('adminPass').addEventListener('keydown',(e)=>{if(e.key==='Enter')loginAdmin()});
q('adminUser').addEventListener('keydown',(e)=>{if(e.key==='Enter')loginAdmin()});
ensureAdminSession();setInterval(()=>{if(adminToken)refreshAll(false)},30000);

